MAKE_LOCATION := ../../make_system/
include $(MAKE_LOCATION)Makefile.platform.mk
include $(MAKE_LOCATION)Makefile.general.mk


LIBRARY_NAME := libPonyTech-LowLevel-Crypto.a
WITH_PLATFORM_SORUCE := yes

LIBRARY_ROOT := ../../
LIBRARY_PATH := $(LIBRARY_ROOT)library/
LIBRARY_INCLUDE := $(LIBRARY_ROOT)include/

include $(MAKE_LOCATION)Makefile.cccompilervar.mk
include $(MAKE_LOCATION)Makefile.library.mk
include $(MAKE_LOCATION)Makefile.cccompiler.mk

