MAKE_LOCATION := ../../make_system/
include $(MAKE_LOCATION)Makefile.platform.mk
include $(MAKE_LOCATION)Makefile.general.mk


LIBRARY_NAME := libPonyTech-FND-Crypto.a
LIBRARY_ROOT := ../../
LIBRARY_PATH := $(LIBRARY_ROOT)library/
LIBRARY_INCLUDE := $(LIBRARY_ROOT)include/
PCH_HEADER := $(LIBRARY_ROOT)include/PonyTech-FND-Crypto/PonyTech-FND-Crypto_DEP.hpp


include $(MAKE_LOCATION)Makefile.cxxcompilervar.mk
include $(MAKE_LOCATION)Makefile.library.mk
include $(MAKE_LOCATION)Makefile.cxxcompiler.mk

